### ISSUE TITLE
optional parameter -par

### ISSUE THREAD

**Issue by BenGodde** [brain-products/BVTools#1]
-par (Paradigm) does not have any effect. No subdir for paradigm build.

BV2BIDS.exe -hdr P06_Piezo1_EEG.vhdr -sub P06 -ses 1 -tsk Loc -par VR -dst C:\Data\

--> C:\DATA\sub-P06\ses-1\eeg  (=built directory structure)

Shouldn't there be a subdir for paradigm within sessions, in case you have different paradigms per sessions?

**Comment by kucint** [comment]
Hi @BenGodde, thanks for the feedback, I will have a look on this issue. I will keep you inform soon.

**Comment by KidistMideksa** [comment]
Hi @BenGodde, let me take over from @kucint and address the issue.

The functionality of the parameter _-par_ is to specify the name of the dataset. The effect can be seen in the _dataset_description.json_ file under the field "Name". This file is generated upon the first conversion to BIDS and by default it's empty (unless specified by the user via _-par_). 

According to the EEG-BIDS [publication](https://www.nature.com/articles/s41597-019-0104-8), this parametaer (-par) shall not create a sub-directory.

In order to aggregate different paradigms per sessions, what you could do is to assign different task name via the parameter _-tsk_. Then the datasets can be distinguished based on the generated "TASKNAME" which will be part of the file name as follows:

....DATA\sub-P06\ses-1\eeg
        
sub-P06_task-**TASKNAME1**_eeg.eeg
sub-P06_task-**TASKNAME2**_eeg.eeg
...

I hope that helps.

**Comment by BenGodde** [comment]
Thanks for clarification. I overlooked the top-level _dataset_description.json_ file.
