### ISSUE TITLE
Can't build the converter

### ISSUE THREAD

**Issue by sodeleoz** [brain-products/BVTools#4]
Hello,

I'm new to using Visual Studio and I really need the BV2BIDS converter which is why I'm eager to know what steps I should do to be able to run the file? 

I've added the repository to the solution explorer and set the FileFormats.BrainVisionToBidsConverterCLI as the startup project and then ran the program. Build succeeded is written in the output, however upon checking the output folder, the application does not open, or if it does, it immediately disappears when I try to type on it. May I know what I'm doing wrong?

Thank you.

**Comment by kucint** [comment]
Hi, you did everything well.
Do you want to run application in VS (debug) or rather without it (just launch)?
I suppose you want to debug the application in VS, right?
if so, follow these steps:
- select **BrainVisionToBidsConverterCLI** as startup project
- just press F5
- because the **BrainVisionToBidsConverterCLI** is a command line application (it does not provide any User Interface) the  console window will open.
- it is possible that the console window immediately closes after app terminates.
if so, disable option in Visual studio that closes the console:
  _Tools->Options->Debugging->Automatically close the console when debugging stops_.
- start the app again and this time you should see following console output:
![image](https://github.com/brain-products/BVTools/assets/54866088/e9bc6b03-60d2-48dc-bea9-ee25ba6776ab)
- as you see, application tells you that you must provide arguments in order to execute converter errorlessly. it gives you hints about argument syntax as well
- you can provide arguments in Visual Studio. To do so:
- open "Project Debug Properties":
![image](https://github.com/brain-products/BVTools/assets/54866088/39be21c3-5256-447b-889c-61aa1f30626c)
- in Command line argument field, provide arguments you want to be passed to the application.
![image](https://github.com/brain-products/BVTools/assets/54866088/26b94a99-f880-48bf-9748-64e270d4076e)
- that's it. let me know if you succeeded.
**Happy Coding!**

**Comment by sodeleoz** [comment]
Hello, 

Thank you for your immediate response. I've tried to input arguments into the command line argument field but don't seem to know if I'm typing it out correctly because I get an invalid syntax.
![image](https://github.com/brain-products/BVTools/assets/125423621/7647935c-e20c-49da-bf22-21e220c192f9)

This is my attempt in writing out the necessary arguments.
![image](https://github.com/brain-products/BVTools/assets/125423621/e38a1c28-2b8f-40da-b2fb-e9d0f727a323)

Thank you again!

**Comment by kucint** [comment]
Hi, 

- _-dst_ and _--bids-destination folder_  depicture the same argument, the first one is the short name, the second one is the long name. you should provide one of them, but not both.
- additionally, you must provide the path to destination folder
- note that you must provide the path to the source heder file that you want to convert as well

So generally your argument list shall look similar to this one:
_-hdr "C:\sourceFolder\FileNameToConvert.vhdr"_
_-dst "C:\destinationFolderToStoreBidsFiles\"_

**Comment by sodeleoz** [comment]
Hello, 
I have been able to convert my files now, thank you very much!

**Comment by kucint** [comment]
Great!
you are very welcome.
